model_path:
  small: './model/mistral-7b-instruct-v0.2.Q3_K_M.gguf'
  large: './model/mistral-7b-instruct-v0.2.Q5_K_M.gguf'

model_type: "mistral"

#embeddings_path: 'sentence-transformers/all-MiniLM-L6-v2'
#embeddings_path: "BAAI/bge-base-en-v1.5"
embeddings_path: 'BAAI/bge-large-en-v1.5'

model_config: 
  'max_new_tokens': 512
  'temperature' : 0
  'context_length': 4096
  'gpu_layers' : 0

chat_history_path: "./chat_sessions/"
